export enum MethodName{
  GET = 'GET',
  PUT = 'PUT',
  PATCH = 'PATCH',
  DELETE = 'DELETE',
  GET_LIST = 'GETLIST',
  POST = 'POST',
  RESTORE = 'RESTORE',
  MANAGE_ROLE = 'MANAGEROLE',
  MANAGE_PERMISSION = 'MANAGEPERMISSION',
}
