export enum ModulesName {
  CATEGORY = 'CATEGORY',
  DESTINATION = 'DESTINATION',
  USER = 'USER',
  AMENTITY = 'AMENITY',
  PROPERTY = 'PROPERTY',
  ROOM = 'ROOM',
  USER_PERMISSION = 'USER_PERMISSION',
  OWNER_REGISTRATION = 'OWNER_REGISTRATION',
  FAVORITE_PROPERTY = 'FAVORITE_PROPERTY',
  BOOKING = 'BOOKING',
  TRANSACTION = 'TRANSACTION',
  ROOMMATE = 'ROOMMATE',
  NOTIFICATION = 'NOTIFICATION',
  PERMISSION = 'PERMISSION'
}
